import { AppConfig } from "../types";

export class CodegenService {
  static generateProjectFiles(config: AppConfig): Map<string, string> {
    const files = new Map<string, string>();

    // package.json
    files.set("package.json", JSON.stringify({
      name: config.app.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      version: config.app.version || "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        "react": "^18",
        "react-dom": "^18",
        "next": "14",
        "lucide-react": "^0.292.0"
      },
      devDependencies: {
        "typescript": "^5",
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        "autoprefixer": "^10",
        "postcss": "^8",
        "tailwindcss": "^3"
      }
    }, null, 2));

    // README.md
    files.set("README.md", `# ${config.app.name}
${config.app.description || "Generated by AI App Generator"}

## Setup
1. \`npm install\`
2. \`npm run dev\`
`);

    // tailwind.config.ts
    files.set("tailwind.config.ts", `
import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "${config.theme?.primaryColor || '#6c8cf5'}",
      }
    },
  },
  plugins: [],
}
export default config;
`);

    // postcss.config.js
    files.set("postcss.config.js", `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`);

    // tsconfig.json
    files.set("tsconfig.json", `
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`);

    // lib/config.ts
    files.set("src/lib/config.ts", `
import { AppConfig } from "../../types";

export const appConfig: any = ${JSON.stringify(config, null, 2)};
`);

    // layout.tsx
    files.set("src/app/layout.tsx", `
import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="${config.i18n?.defaultLocale || 'en'}">
      <body>{children}</body>
    </html>
  );
}
`);

    // globals.css
    files.set("src/app/globals.css", `
@tailwind base;
@tailwind components;
@tailwind utilities;
`);

    // page.tsx
    files.set("src/app/page.tsx", `
import { appConfig } from "../lib/config";

export default function Page() {
  return (
    <main className="p-8">
      <h1 className="text-3xl font-bold mb-4">{appConfig.app.name}</h1>
      <p>{appConfig.app.description}</p>
      <div className="mt-8">
         {/* Generated UI will connect here in actual exported project */}
         <p>This is a starting point. Start building your components based on the config.</p>
      </div>
    </main>
  );
}
`);
    
    // .env.example
    files.set(".env.example", `NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1\n`);

    return files;
  }
}